### ISSUE TITLE
Using Cache\UserContextSubscriber with Bundle\Listener\UserContextSubscriber

### ISSUE THREAD

**Issue by rederrik** [FriendsOfSymfony/FOSHttpCacheBundle#206]
Hey,

Is it even possible to use FOS\HttpCacheBundle\EventListener\UserContextSubscriber 
to generate context hash while using Symfony HttpProxy? 
As I can see FOS\HttpCache\SymfonyCache\UserContextSubscriber::generateHashLookupRequest marks the request as internal, and the first line of Listener\UserContextSubscriber::onKernelRequest makes sure this is not a sub-request.
I'm confused. How do I use it then?
Or am I supposed to create my own generator to use with Symfony HttpProxy?

Thanks.

**Comment by dbu** [comment]
afaik this works inside ez publish. internal request is only used inside the proxy class, its not the same as the request type.

you can debug whether the hash lookup works with something like `curl -H "Accept: application/vnd.fos.user-context-hash" -v http://yourhost.domain/_fos_user_context_hash -o /dev/null` (if it fails, remove the -o part to see the actual output)

**Comment by dbu** [comment]
you will need to comment out the caching proxy kernel in app.php or comment out the sanity check in UserContextSubscriber::preHandle (skip the whole method, as you want to see the result of the hash lookup yourself, to see if the lookup worked)

**Comment by rederrik** [comment]
I actually want to use symfony proxy since I don't have Varnish. After reading the docs I had an impression that included hash generating listener is supposed to work with both Varnish and Symfony HttpCache, but it looks like its not true, since it wont respond to internal requests for hash sent by Symfony proxy.
But yeah, it works fine after disabling that check.

Oh well, it looks like I'll have to implement my own subscriber for this.

**Comment by dbu** [comment]
@rederrik the listener for hash lookup is supposed to work with the symfony http cache as well. as said, the concept of the request being internal is only used within the event subscriber that is hooked into the kernel. the listener for hash lookup only checks if there is a master request, which is not the same.

try to run the code in a debugger or sprinkle your code with var_dumps and die() to see what is going on. i would expect that the hash lookup request fails because of a configuration mismatch or because something is missing in the documentation.

**Comment by rederrik** [comment]
I feel very silly since it works fine now.
Maybe class cache is to blame, I have no other idea since rebaking it was the only thing I done. I thought it's supposed to renew each cache:clear command.

Anyways, it's all good now, thank you for your support.

**Comment by dbu** [comment]
glad it worked out!
