### ISSUE TITLE
Fix TagSubscriberTest:95

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCacheBundle#214]
Any idea why this is [failing](https://travis-ci.org/FriendsOfSymfony/FOSHttpCacheBundle/builds/65356500) on 2.7 (but not on 2.7@dev and < 2.7). Build failure introduced with https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/commit/8a42717c160ad92200e02301e3538fd549f28904.

**Comment by dbu** [comment]
i think we only discovered the failure with that commit, it must have happened earlier.

my suspicion is that the behaviour of when a request is considered the master request has changed with 2.7 and the problem is around https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/EventListener/TagSubscriber.php#L84
