### ISSUE TITLE
custom_proxy_client not working

### ISSUE THREAD

**Issue by thuynh** [FriendsOfSymfony/FOSHttpCacheBundle#234]
I ran into an issue with the custom proxy client not working as intended. The error message i'm getting is **You need to configure a proxy_client or specify a custom_proxy_client to use the cache_manager**. I can't figure out what the problem may be. Here is the code. 

fos_http_cache.yml
```
fos_http_cache:
    cache_manager:
        enabled: true
        custom_proxy_client: company.varnish.client
    tags:
        enabled: true
```

services.xml
```
<service id="company.varnish.client" class="Company\CoreBundle\Component\VarnishProxyClient">
    <argument type="service" id="company.load.balancer.manager" />
    <argument type="service" id="company.site_setting.repository" />
</service>
```
VarnishProxyClient.php
```
<?php

namespace Company\CoreBundle\Component;
use Company\CoreBundle\Entity\SiteSettingRepository;
use FOS\HttpCache\ProxyClient\Varnish;
use Guzzle\Http\ClientInterface;

class VarnishProxyClient extends Varnish
{

	/**
	 * @var LoadBalancerManager
	 */
	protected $loadBalancer;

	/**
	 * @var string
	 */
	protected $domain;

	/**
	 * @param LoadBalancerManager $loadBalancer
	 * @param array $servers
	 * @param null $baseUrl
	 * @param ClientInterface $client
	 */
	public function __construct(LoadBalancerManager $loadBalancer, SiteSettingRepository $settings, ClientInterface $client = null)
	{
		$this->domain = $settings->get('domain');
		parent::__construct([$this->domain], $this->domain, $client);
		$this->loadBalancer = $loadBalancer;
	}

	/**
	 * Override the domain to invalidate
	 *
	 * @param $domain
	 *
	 * @return $this
	 */
	public function setDomain($domain)
	{
		$this->domain = $domain;
		return $this;
	}

	/**
	 * {@inheritdoc}
	 */
	protected function queueRequest($method, $url, array $headers = array())
	{
		$ipAddresses = $this->loadBalancer->getInstanceIpAddresses();
		if (0 === count($ipAddresses)) {
			parent::queueRequest($method, $url, $headers);
		}
		else {
			foreach ($ipAddresses as $ip) {
				$headers['Host'] = $ip;
				$headers['X-Forwarded-Domain'] = $this->domain;
				parent::queueRequest($method, $url, $headers);
			}
		}
	}
} 
```

**Comment by dbu** [comment]
this looks like a bug at https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/DependencyInjection/Configuration.php#L55

i think we messed up with the naming. can you to change https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/DependencyInjection/Configuration.php#L57 to say "custom_proxy_client" instead of "proxy_client"? there is no proxy_client configuration inside the cache_manager...

if that solves the problem, please create a pull request. if you have the time, the best would be to also add a test about custom_proxy_client to the configuration unit test https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/Tests/Unit/DependencyInjection/ConfigurationTest.php - then we can be sure it won't break again later.

**Comment by thuynh** [comment]
When setting to custom_proxy_client, this is what I'm now getting:

```
ContextErrorException in FOSHttpCacheExtension.php line 75:
Notice: Undefined index: proxy_client
```

I got pass that by setting

```
fos_http_cache:
    cache_manager:
        enabled: true
        generate_url_type: false
        custom_proxy_client: company.varnish.client
    tags:
        enabled: true
```

Then got the following error:

```
ContextErrorException in FOSHttpCacheExtension.php line 92:
Notice: Undefined index: proxy_client
```

**Comment by dbu** [comment]
@thuynh any chance you can add tests for this and try a pull request to fix the problem? otherwise i can try to do that next week when i find time.
