### ISSUE TITLE
Call to undefined method ...CacheManager::addSubscriber()

### ISSUE THREAD

**Issue by dantleech** [FriendsOfSymfony/FOSHttpCacheBundle#260]
In `master` I get this error.

It is because the `addSubscriber` method has been removed from the `CacheManager`. Should we instead be tagging the logger as a `kernel.subscriber`?

**Comment by dantleech** [comment]
Hmm, this branch is also still referening the `TagHandler` -- is there a missing PR somewhere?

**Comment by dbu** [comment]
master is at the moment still in the flow and rather unstable. if the tests do not show this one, its likely we miss some functional test.

likely, its broken by https://github.com/FriendsOfSymfony/FOSHttpCache/pull/237. i don't think we have a pull request open on the bundle that would adress the issue - yet.

we also have to check one more time whether the TagHandler system is now really future proof.

**Comment by dantleech** [comment]
hmm, I will see if I can update to match the new changes.

**Comment by dantleech** [comment]
actually it doesn't seem to be so simple, e.g. 

- is the `ResponseTagger` meant to be used as an independent service? or as a dependency for the `CacheManager`?
- Which class actually tags the `Response` object?

/cc @andrerom @ddeboer

**Comment by andrerom** [comment]
I'm not sure, we never discussed the bundle but @dbu was involved so he might have an idea.

**Comment by dbu** [comment]
in the lib, we plan to add a tagPsrResponse method for PSR-7 to the
ResponseTagger. my idea was that in the bundle, we extend that class to
add symfony HttpFoundation Response support to it and use that class
from the listener. the idea was that adding a tag is not the job of the
CacheManager.

but now that we look into making tagging more flexible/pluggable, i am
not 100% sure the architecture is perfect yet. there should not be
several parts that need to be set up independently when choosing whether
to do in-band tagging or out-of-band.

**Comment by dantleech** [comment]
> there should not be several parts that need to be set up independently ..

The assumption with the ResponseTagger (and the proxy client TagsInterface) is that the tags will always be sent as headers - which is always the case - I believe - at least at the moment. What additional parts are you referrring to?

Shall I just go ahead and integrate the component's master branch here?

**Comment by dbu** [comment]
i started on updating in #235 but then ended up with a heavy case of yak-shaving on php-http because things changed and i worked on https://github.com/FriendsOfSymfony/FOSHttpCache/pull/257 which in turn led me to fix things with php-http. if you want to work on that at this point, best would be to start with the library PR 257... i will try to find some time for that soonish, but i have rather busy holidays ahead.

the discussion on tagging is at https://github.com/FriendsOfSymfony/FOSHttpCache/issues/265 and the idea is to make it more general to also support out-of-band tagging. that might change the setup one more time i fear.

**Comment by dbu** [comment]
this has been fixed afaik
