### ISSUE TITLE
configure strict mode

### ISSUE THREAD

**Issue by wickedOne** [FriendsOfSymfony/FOSHttpCacheBundle#278]
as a result of https://github.com/FriendsOfSymfony/FOSHttpCache/issues/270 being solved & merged, have the ability to configure strict mode.

will have a go at this somewhere this week.
question beforehand: any ideas on where to put this in the configuration? currently strict mode only applies to tagging, but i can imagine it can be applied to other (future) validations in the library…

**Comment by dbu** [comment]
i would make that a specific configuration inside the tagging part. we
could later add a global strict switch that changes the default for
specific strictness - but you want to be able to make specific things
strict or not.

**Comment by wickedOne** [comment]
ok, this is going to take a little more time as expected as this bundle isn't up to date with the ``FOSHttpCache`` structure (e.g. still makes use of the refactored [``TagHandler``](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/Handler/TagHandler.php#L5)).  
does dat have to come in a seperate issue / pr, or can i have a go at that in this one?

**Comment by dbu** [comment]
oh, indeed. i was delaying on this because
https://github.com/FriendsOfSymfony/FOSHttpCache/pull/253 will probably
refactor tagging one more time, and there is also
https://github.com/FriendsOfSymfony/FOSHttpCache/issues/265

if you want to update it could still be useful because future
refactorings would handle smaller steps instead of everything being
totally out of sync. if you do, i would prefer a separate pull request
to make it easier to review. if 265 would interest you, that would be
awesome. its the last larger moving part of FOSHttpCache before we get
ready for the 2.0 release.

**Comment by wickedOne** [comment]
265 sounds really interesting, not sure whether i'll be able to find enough time or have enough knowledge about out of band tagging to put it together…
will have a look at it though.

meanwhile i'll do a small refactor to get ``FOSHttpCacheBundle`` back in line with ``FOSHttpCache`` so the strict mode at least can be implemented

**Comment by dbu** [comment]
:+1:
