### ISSUE TITLE
[RFC] Do not force client for TagHandler or other one

### ISSUE THREAD

**Issue by joelwurtz** [FriendsOfSymfony/FOSHttpCacheBundle#281]
When using the TagHandler user have to set a proxy client to do the invalidation. 

However we got an use case where we have multiple applications, and one is doing the invalidation and the other only set the tags and we are forced to set a client in the second one but it's useless in this case.

I don't know if the current architecture of TagHandler allow to only add tag on response without having a Client ? If it's the case, can this be separated in another class and remove the dependency ?

**Comment by dbu** [comment]
thanks for this input. we are trying to figure out how to abstract the tag handling (https://github.com/FriendsOfSymfony/FOSHttpCache/pull/253 and https://github.com/FriendsOfSymfony/FOSHttpCache/issues/265) - i think this is another good input to take into consideration.

i think currently the tag handler is the same class for recording tags and for invalidating. maybe we indeed should separate those functionalities.

**Comment by ddeboer** [comment]
While some things have changed in the library since this issue was opened (in particular, TagHandler was removed), the original problem of separating the concerns of *setting* tags and *invalidating* them still stands.

(https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/src/ResponseTagger.php) relies on a `TagCapable` (proxy client) only for its `getTagsHeaderName()` and `getTagsHeaderValue(array $tags)` methods:

- the name of the HTTP header must be known both when setting and invalidating tags (that are stored in that HTTP header);
- `getTagsHeaderValue()` formats the tags so that they can be invalidated later (e.g., by separating them with some character convention).

The only way I see to remove the direct coupling between ResponseTagger and TagCapable is to introduce a third object that is shared between them and holds the header config and does the formatting. Do you see any other (better) ways?

**Comment by dbu** [comment]
i guess the shared object is the best architecture we can do. this would need some changes in FOSHttpCache as well. we have a beta 1 there, but i would say beta still allows us to fix this. its only a change in the application setup and easily discovered - not some surprising change in a method signature or such.

the reason we inject in this direction is that the formatting of tags is specific to the caching proxy. there might be other ways to tag a response than what we currently have. but i think having a tag formatting strategy would make sense. then we can do CommaSeparatedTags now and other things as we need them later.

@joelwurtz feel like doing a pull request on FOSHttpCache for this?

**Comment by Toflar** [comment]
Can anyone here explain me why the proxy client should be responsible for providing the tags header name and the value (or is this discussion actually about why this is, sorry maybe I didn't get it 😄 )? Let's face it, in 99.99% of all cases this will look something like this:

```
(X-)Cache-Tags: tag1,tag2,foobar
```
I don't understand why Varnish would want a different header than the Symfony Reverse Proxy. I think it's wrong to delegate this responsibility to the proxy. At the end of the day, this is just a header and it has to match your proxy configuration.
I think I would do something like this:

```php
class ResponseTagger
{
    public function __construct(TagHeaderProcessorInterface $processor);
    public function addTags();
    public function tagResponse(ResponseInterface $response, $replace = false)
    {
        if (!$this->hasTags()) {
            return $response;
        }
        if ($replace) {
            return $response->withHeader($this->processor->getTagsHeaderName(), $this->processor->getTagsHeaderValue($this->getTags()));
        }
        return $response->withAddedHeader($this->processor->getTagsHeaderName(), $this->processor->getTagsHeaderValue($this->getTags()));
    }
```

That's the easiest way I can think of. Any service can use the response tagger to add tags and we can provide multiple implementations of the `TagHeaderProcessorInterface` (find me a better name please 😄 ) to support different formats. If you start with the Symfony Cache and it expects the header to be named `Symfony-Cache-Tags` then you use the appropriate processor. If you then switch to Varnish and you want to get rid of the `Symfony` part in the header (for whatever reason)  or the tags should not be comma-separated but a regular expression or something instead, you switch to a different processor. Each processor again might have different configuration options.

**Comment by dbu** [comment]
the idea is that the client interacts with the caching proxy, and thus its the client that knows about the header name and formatting of the value. declaration and invalidation of tags needs to be compatible.

i think the reason we built things like this was to avoid that the ResponseTagger can use a wrong header name and to separate the formatting of the tags header value from the ResponseTagger.

i like your idea @Toflar 

we could outsource the header name and header value to a `TagHeaderFormatter` and provide a default implementation `CommaSeparatedTagHeaderFormatter`. ResponseTagger would require a TagHeaderFormatter instance instead of the ProxyClient. the ProxyClient would accept a TagHeaderFormatter instance instead of the configuration for the header name. if none is supplied, it instantiates the comma separated with the current default header name. TagCapable can instead of the tag header methods provide a getTagHeaderFormatter() method. then we can document to set up ResponseTagger with $proxyClient->getTagHeaderFormatter() to promote consistency. scenarios like @joelwurtz describes would be handled by creating ResponseTagger with a `new CommaSeparatedTagHeaderFormatter` instead, to avoid the proxy client. in that scenario you anyways have to make sure the 2 applications are in sync, or things will fail horribly.

does that make sense? and do you want to do a pull request to FOSHttpCache @Toflar ? the cache is in beta already, so BC is a bit of a concern. but i think its a clear improvement, and all BC issues clearly show when instantiating, so i am in favor of changing it now rather than carry backwards compatibility hacks around.

**Comment by Toflar** [comment]
Sure, that sounded like a piece of cake. Here we go https://github.com/FriendsOfSymfony/FOSHttpCache/pull/353 :)

**Comment by dbu** [comment]
https://github.com/FriendsOfSymfony/FOSHttpCache/pull/354 will fix this. but we will need to adjust the bundle as well once that is merged. @Toflar do you want to look into that as well or should i?

**Comment by Toflar** [comment]
I won't say no if you can look at it. For now, I'm only using the bundle for my replay headers story. I just contributed to this issue to help making the bundle/lib 2.0 stable but I still haven't looked at all the configuration options possible so it would certainly be a bigger effort for me as I think you know the options by heart 😄
