### ISSUE TITLE
Set up the hash generation route for anon acess by default

### ISSUE THREAD

**Issue by gggeek** [FriendsOfSymfony/FOSHttpCacheBundle#301]
If that is not possible, at least document clearly that the hash-generation route:
- should be inside the same firewall as the main app
- should be available to anonymous users

The discussion for the need for this setup is at https://github.com/FriendsOfSymfony/FOSHttpCache/issues/287

**Comment by dbu** [comment]
afaik it is not possible for a route to define its own security. otherwise the login of e.g. FOSUserBundle would surely do that, and it does not. we need to have our listener after security so that we can use the role system to build the hash built on the symfony roles...

regarding documentation: after the discussion in the other issue, i tried to clarify this, it was indeed very unclear. note that i did not tag the library or bundle since adding that doc, so you only see this when browsing "latest" but not for "stable" yet.

the configuration section now looks like this: http://foshttpcachebundle.readthedocs.io/en/latest/features/user-context.html#configuration

and the library configuration even got this warning: http://foshttpcache.readthedocs.io/en/latest/user-context.html#user-context-hash-from-your-application

if you have suggestions for further improvement, i am of course glad to hear them or get pull requests to the relevant files.
