### ISSUE TITLE
Cache-Control: max-age=0, no-cache

### ISSUE THREAD

**Issue by f3rch0** [FriendsOfSymfony/FOSHttpCacheBundle#317]
Hi, i'm using this config:

`fos_http_cache:
    user_context:
        enabled: true
        role_provider: true
    cache_control:
        defaults:
            overwrite: true
        rules:
            -
                match:
                    path: ^/
                headers:
                    cache_control:
                        private: true
                        max_age: 60
                        s_maxage: 60
                        must_revalidate: true
                        proxy_revalidate: true
                    etag: true
                    vary: [Accept-Encoding]`

Nevertheless, the header Cache-Control always has max-age=0 and no-cache no matter what config i change. Even setting overwrite to false and putting annotation @Cache in the controller forcing the max-age to 60 nothing happens. But when i disable the bundle and use @Cache annotation it works perfectly..

**Comment by dbu** [comment]
i am a bit confused why you have `private: true` and then `s_maxage: 60`. s-maxage is the lieftime for for caching proxies, while private means caching proxies should never cache this.

can you try to remove things from this configuration? if private was intended, remove everything else except max_age - the rest is irrelevant if the proxy must not cache the response. otherwise try to remove the private: true and then remove the headers one by one to see if a specific header is causing the issue.

afaik in app_dev mode, symfony will always send no-cache, so you would need to use the production mode and have to clear the cache after each configuration change as in production mode symfony will not check for config changes.

**Comment by f3rch0** [comment]
You're right... i've changed the parameters that you mention and tested again in both environments (dev and prod) but without success, it keeps sending max-age=0, no-cache.

**Comment by dbu** [comment]
can you try to debug the CacheControlSubscriber class and see if it gets triggered or if you can see if it does not match the request or if there is some other problem? use a step-by-step debugger, or if you don't have one the good old var_dump method to see where in that class you get and if it does try to set the headers at all or not.

**Comment by f3rch0** [comment]
Did that and i found that the UserContextSubscriber was setting always max-age and no-cache option. The problem was the session.name that didn't have the right name and the hash didn't match in any request.
Problem solved, thanks for your help.

**Comment by dbu** [comment]
ah, great you found it. yeah, that makes sense. when the session hash
does not match, we disable caching as otherwise caches could get mixed
up between permission levels, which is way worse than no caching...
