### ISSUE TITLE
Dynamic Varnish servers

### ISSUE THREAD

**Issue by plozmun** [FriendsOfSymfony/FOSHttpCacheBundle#361]
I have a service definition where i got varnish ips from amazon service. Is it posible to set this service on 'servers' parameter on Varnish definition? I try to do it but it seems that only accept an array. How can I dynamically implement it?

**Comment by dbu** [comment]
do the cloud servers report their ips to all instances of your symfony application? if they do, you could extend the proxy client (resp. HttpDispatcher) in verison 2 to fan out requests dynamically. i will do a small refactoring to the HttpDispatcher right now to make it more extensible with regard to the server ips.

the solution i ended up using in a cloud project was to use a message queue. we have a message queue client instead of a varnish client, which sends invalidation requests into a message queue, and each varnish instance has a php worker kept alive by supervisord (a simple php class using FOSHttpCache without symfony) that listens for messages and sends invalidation requests to localhost. that way we need no central knowledge of varnish instances.

**Comment by dbu** [comment]
see https://github.com/FriendsOfSymfony/FOSHttpCache/pull/352

**Comment by plozmun** [comment]
Ok, i will extend the proxy client. Thank you
