### ISSUE TITLE
Add support for Weak Etag's

### ISSUE THREAD

**Issue by NavyCoat** [FriendsOfSymfony/FOSHttpCacheBundle#383]
I've got problem with nginx and weak etags generated by it.

I'm using your bundle to generate etags for my responses, and i found that when use it with enabled **gzip** on Nginx they are changed to weak Etags, due to gzip compression that breaks byte-to-byte equality. That etag is next send to client and it receives something like `W/"foobarbaz123"` instead `foobarbaz123`.

When client made request with `If-None-Match` using that weak etag, nginx pass it to application and it is still weak etag.

The question is, can we add support for that case? Maybe optional `weak-etag` parameter to set?
I found that modifing line 136 in CacheControlSubscriber and set opitonal `weak` parameter to true solves problem. But maybe there is more appropriate solution for this?

**Comment by dbu** [comment]
would it make more sense to have a separate config weak-etag, or an option
on the etag config? i think the easieat is to relax the etag field from
boolean to text ("hard" / "weak" / false) with bool true meaning "hard".
want to do a PR for this? (only for master, not the 1.x versions)

Am 07.09.2017 3:02 nachm. schrieb "Sebastian Tkaczyk" <
notifications@github.com>:

I've got problem with nginx and weak etags generated by it.

I'm using your bundle to generate etags for my responses, and i found that
when use it with enabled *gzip* on Nginx they are changed to weak Etags,
due to gzip compression that breaks byte-to-byte equality. That etag is
next send to client and it receives something like W/"foobarbaz123" instead
foobarbaz123.

When client made request with If-None-Match using that weak etag, nginx
pass it to application and it is still weak etag.

The question is, can we add support for that case? Maybe optional weak-etag
parameter to set?
I found that modifing line 136 in CacheControlSubscriber and set opitonal
weak parameter to true solves problem. But maybe there is more appropriate
solution for this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/issues/383>, or mute
the thread

**Comment by NavyCoat** [comment]
Okay @dbu, I've made it.

**Comment by dbu** [comment]
great! will look at this on monday, i am still on holidays this week ;-)

**Comment by dbu** [comment]
fixed in #384

> release

i created https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/milestone/5 - there is one thing that should be fixed, and i'd love to have tests running for php 7.2. if you would have time to look what goes wrong with the 7.2 build, that sure would help a lot. the other thing is not a blocker for releasing, its a fix that is important but its been broken probably since forever.

**Comment by dbu** [comment]
fixed in #384
