### ISSUE TITLE
Fix ContextInvalidationLogoutHandler

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCacheBundle#392]
In #390 we replaced the test session handler with the ArrayMockSessionHandler that behaves a lot closer to the real NativeSessionHandler. We now have to skip the ContextInvalidationLogoutHandlerTest because it does not work. The problem is that SecurityBundle SecurityExtension puts `security.logout.handler.session` as the first handler of the session logout handler. The logout handlers seem to not have priorities. That means that the session is already destroid when our context invalidation handler is executed, and it does not have access to the session id anymore.

~There is a 3rd parameter TokenInterface to the LogoutHandlerInterface::logout method. would that be what we need?~ (no, its the username and password thingy) 
we could try to decorate the successhandler, because that is called first.

On a side note: the accept header is not used in BAN by the default ban vcl. should we add handling for that?

**Comment by wesnick** [comment]
I was looking into this because it had the potential to affect a project I am working on.  The current behavior does not produce undesired results except in 1 configuration scenario:

[session_invalidate](https://symfony.com/doc/current/reference/configuration/security.html#invalidate-session) is true, but delete_cookies does not remove your session cookie, then you could be served stale content from cache

Other scenarios it doesn't matter either because session has been destroyed, so cache entry is orphaned, or cookie is deleted from session, so it will not be served.  In either case the cache entry is orphaned.

I think rather than decorate the successhandler, it might be better to replace SessionLogoutHandler, if it is enabled, with the ContextInvalidtionHandler, which in turn, invalidates the session if the configuration options is set.

**Comment by dbu** [comment]
i think the scenarios where we have a problem are:
* not restarting the session (poor configuration, but could happen)
* when deleting the session cookie on the client fails (not very likely)
* when a session cookie has been stolen

i am mostly worried about the 3rd situation. logging out is meant to destroy the session, and if the listener does not work we don't really keep that promise. this is not a security hole per se (if you can steal cookies, there is a huge security problem already) but if you have long-lived session cookies, it can escalate the problem if a security problem exists in the first place.

i am afraid of replacing symfony security services and would prefer to keep the interaction as light as possible. if we do a custom success handler that is injected the default success handler, the user can configure that success handler instead of we add a handler thats executed too late.

**Comment by dbu** [comment]
@wesnick any feedback on my reflections?

**Comment by wesnick** [comment]
It seemed to me that another bundle or a project's own logout success handler could potentially re-decorate or re-replace this custom success handler, or vise-versa, causing difficult to find failures.  Perhaps this could be overcome by adding the functionality in a trait, and using this trait in a custom success handler, but documenting how to reuse for other use cases.

Both options require complex configuration behaviors.  Another thought is to maybe just add a memento to the current logout handler with the original session ID that is set by some other event, but this adds unwanted state to the listener.

**Comment by wesnick** [comment]
I was taking a look at this.  Decorating the success handler is quite difficult. The default service is abstract, accepts parameters from main security configuration.  The more I probed, the more ugly the solution became.  I am not clever enough to figure out how to do this in a DI extension.

SessionLogoutHandler only has a single global implementation.  This approach feel less interventionist.  I will do a quick POC.  No committments!
