### ISSUE TITLE
Does that bundle also work with AWS CloudFront?

### ISSUE THREAD

**Issue by thomas-dotworx** [FriendsOfSymfony/FOSHttpCacheBundle#406]
I'm currently trying to use AWS CloudFront and Lambda@Edge for caching. Does anyone have experience with that? I'm currently stuck with session IDs and user context hashes getting mixed up.

Here's my Lambda code that is executed on "Viewer Request" event:
```es6
'use strict';

function parseCookies(headers) {
    const parsedCookie = {};
    if (headers.cookie) {
        
        console.log(`${headers.cookie[0].value}`);
        
        headers.cookie[0].value.split(';').forEach((cookie) => {
            if (cookie) {
                const parts = cookie.split('=');
                parsedCookie[parts[0].trim()] = parts[1].trim();
            }
        });
    }
    return parsedCookie;
}

exports.handler = (event, context, callback) => {
    const request = event.Records[0].cf.request;
    const headers = request.headers;
    
    const https = require('https');
    
    console.log(request);
    
    // Read session cookie
    const parsedCookies = parseCookies(headers);
    let sessionId = '';
    if (parsedCookies && parsedCookies['PHPSESSID']) {
        sessionId = parsedCookies['PHPSESSID'];
        
        request.headers.cookie[0].value = '';
    }
    console.log(`SessionId: ${sessionId}`);
    
    // Send request to origin host at /_fos_user_context_hash
    // passing the original session cookie
    const options = {
        hostname: `mydoma.in`,
        port: 443,
        path: '/_fos_user_context_hash',
        method: 'HEAD',
        headers: {'Cookie': `PHPSESSID=${sessionId}`, 'Accept': 'application/vnd.fos.user-context-hash'}
    };
    
    const req = https.request(options, (res) => {
      console.log('statusCode:', res.statusCode);
      console.log('headers:', res.headers);
    
      // Read the X-User-Context-Hash from the hash endpoint
      const headerName = 'X-User-Context-Hash';
      let hash = 'anonymous';
      
      if (res.headers[headerName.toLowerCase()]) {
        hash = res.headers[headerName.toLowerCase()];
      }
      // Reset all cookies
      request.headers.cookie = [];
      // Append X-User-Context-Hash before passing request on to CF
      request.headers[headerName.toLowerCase()] = [{ key: headerName, value: hash }];  
      
      callback(null, request);
    
    }).on('error', (e) => {
      console.error(e);
      // Forward request anyway
      callback(null, request);
    });
    
    req.end();
}
```

**Comment by dbu** [comment]
interesting! i never tried to use user context with AWS but looking at what you do, it should be possible. when you figure it out, i would be very interested in reading how it works. we could add a section in the doc, or link to a blogpost if you write one.

i am not familiar with the lambda @ edge, so i will just try to summarize what should happen:

when a request comes in, we look for the session cookie and delete all other cookies to not have variance because of google analytics and the like. we then do the hash lookup with the session cookie (and/or basic auth). the hash lookup uses the special accept type and needs to be configured on symfony side. the hash lookup request should be cached with vary by cookie to not constantly send requests. on proxy side, when hash lookup response comes, the original request is restarted but with the hash key in the special header. we keep the session cookie in place. on symfony side, the page is rendered like normal (with the rights of the current user) but if the page only depends on the role and not the individual user, cache instructions are sent, along with a `Vary: X-User-Context-Hash` header to make the cache act per group.

in the vcl example we provide, we just delete all other cookies to avoid problems and let normal caching rules decide. i am not sure if you do that, i think your code instead deletes the session if there is one, which would make you always end up with the anonymous version of the page. in the place where you receive the hash response, be aware that even anonymous users are in a "group" and also get a hash from the application.

some debugging ideas: does the firewall cover `/_fos_user_context_hash` ? do you get back a hash from there? and if you send the hash and a valid session id, do you get the expected page?

**Comment by thomas-dotworx** [comment]
Thanks for you quick answer!

I'll be happy to update the docs as soon as I figured out how to use it. What I currently do:
* only forward the session id (no other cookies) to the hash lookup, that works fine
* take the generated hash and pass it in the 'X-User-Context-Hash' header to the symfony application. In my example above I did not pass any cookies to the application. I changed that now and will update my post if I got results.
* I added another trigger (in Lambda@Edge) that removes all "set-cookie" headers from the response before it gets stored to the cache. Do I need to manually add the "Vary: X-User-Context-Hash" header here?

**Comment by dbu** [comment]
1. exactly
2. the idea is that the application renders the page exactly like "normal", with a concrete user. but if the outcome only depends on the user's group and not the individual user, the application sets the Vary: X-User-Context-Hash header. if it depends on the individual user, it must set Vary: Cookie. the thing is that either way we force the proxy to cache even if there is a cookie, because we know the application is handling this correctly
3. set-cookie only happens when you removed the session cookie, thus destroying the context and making symfony think this is a new request. and the vary header should always be set by the application, not the proxy.

if all you want to achieve is to only ever render anonymous pages, i would make the proxy remove all cookies and configure symfony to not start sessions. then you don't need the hash.

**Comment by thomas-dotworx** [comment]
Thanks for your help and your hints. It's actually looking good now. As soon I've got a final version I'll let you know so we can update the docs.

**Comment by thomas-dotworx** [comment]
One thing that I'm still not sure about: You do not pass the `REMEMBER` cookie to the hash request, do you?

**Comment by dbu** [comment]
hm, in the varnish vcl we completely break the rememberme functionality i think. it would make sense to define an exception for that so that autologin still works. the response would be a set cookie page, so caching should not happen anyways. how does rememberme work, does that happen on any page, or only after a redirect to the login page, and then automatically redirect back to where the user came from?

**Comment by thomas-dotworx** [comment]
Sorry, my question was not precise. I use the rememberme functionality of symfony, so here's a case that could happen.
* User is logged in and checked the `REMEMBERME` option
* The session expires
* User opens a page
* The request to /_fos_user_context_hash is triggered with a new (or even without) session id
* The response from /_fos_user_context_hash will be a hash for a logged out user, although the user is logged in via the `REMEMBERME` cookie

I think that issue could be solved by not only passing the `PHPSESSID` cookie but also the `REMEMBERME` cookie to the hash endpoint. Does that make sense or does the bundle handle that case and I just didn't see it? Thanks

**Comment by dbu** [comment]
that is in the end your choice ;-) but i think in general we should. the login without rememberme can also not be cached, so its no big loss. i think our configs should allow that cookie - if a dev does not want rememberme, they simply should disable the feature in the first place and then the configuration can still allow rememberme - it will simply never exist.

if you successfully test the assumption 2, i will update the vcl and symfony http cache configs to support rememberme and add a note in the documentation.

**Comment by thomas-dotworx** [comment]
I just updated my config to pass the `REMEMBERME` cookie, that works fine for me.

In my Lambda@Edge function that looks like that:
```es6
let cookie = '';
    if (parsedCookies) {
        if(parsedCookies['PHPSESSID']) {
            cookie = `PHPSESSID=${parsedCookies['PHPSESSID']}`;
        }
        if(parsedCookies['REMEMBERME']) {
            if (cookie.length > 0) {
                cookie += ';';
            }
            cookie += `REMEMBERME=${parsedCookies['REMEMBERME']}`;
        }
    }
    
    // Send request to origin host at /_fos_user_context_hash
    // passing the original session and rememberme cookie
    const options = {
        hostname: `${request.headers.host[0].value}`,
        port: 443,
        path: '/_fos_user_context_hash',
        method: 'HEAD',
        headers: {
            'Cookie': cookie, 
            'Accept': 'application/vnd.fos.user-context-hash',
            'Vary' : 'Cookie'
        }
    };
```

**Comment by dbu** [comment]
great! can you do a pull request to the doc to add a tip, or write a blogpost with this?
