### ISSUE TITLE
Authenticated vs non authenticated

### ISSUE THREAD

**Issue by Webonaute** [FriendsOfSymfony/FOSHttpCacheBundle#547]
Hi.

I would like to add cache to only non authenticated user on a endpoint. what configuration I should use?

that endpoint varie a lots when user is authenticated but pretty all time the same when user is not logged in. I dont want to cache content when user is login because miss ratio is way too high.

is there a way out of the box to do that?

**Comment by dbu** [comment]
out of the box, varnish does not cache at all when there is a session cookie. if you can make sure that you only have a session cookie when users are logged in, but have no cookie otherwise, this will work.

if there is a cookie, varnish can't tell if there is a session or not. if you always have the session, you need to make sure that the caching headers tell varnish to not cache, even though it could. if you can guarantee that, you can configure varnish to cache even when there is a session and without doing the whole user context configuration. there is no configuration option for this - and i would recommend to do a response listener that comes after this bundle and overwrites the caching header to not cache if there is an active session. it probably also needs to force no-cache if there is for example a csrf token for a form.
