### ISSUE TITLE
Empty flash_messages cookie in tests with v2.9.1

### ISSUE THREAD

**Issue by spointecker** [FriendsOfSymfony/FOSHttpCacheBundle#558]
Hi,

when upgrading to version 2.9.1 my tests fail due to empty cookie jar of flash messages in tests.
With version 2.9.0 everything works just fine.
I have seen that version 2.9.1 should fix something with multiple redirects and flash messages, so I guess this has something to do with that.
Do I need to make any changes in my code / config?

**Comment by dbu** [comment]
hm, tricky one. #548 changed this to only add the flashes when the answer is no longer a redirect response. i would expect that in real world use, the result is the same and the test failure is because you expect the cookie to be set on the redirect response already? 
however, even if that is the case there is one real problem: when the session is destroyed before redirecting ends (e.g. logout involves multiple redirecting requests, or redirecting to a public part of the website that does not have sessions), we now lose the flash messages.

looking at the relevant code, i see that we do an `array_merge` of existing flashes in a cookie. the specific test case in #548 indeed does not work with array_merge, because we have two flashes with the same key. the actual difference is that now, if we already have flashes with a key, we add more messages with the same key rather than overwrite the existing messages with the same key.

i think we should revert the cookie handling. to keep the newly introduced behaviour of not overwriting messages with the same key, we can change from array_merge to [array_merge_recursive](https://3v4l.org/sIFJ9). that should be more reliable. (if a frontend somehow manages to consume the flash message cookie while doing a redirect, it is imho to be fixed in the frontend and not in the backend - and afaik normal web browsers simply follow redirects without rendering the page, so javascript that would consume the flash message is not even loaded)

@ismailcherri can you double check if my thinking is correct, or am i missing something?

**Comment by ismailcherri** [comment]
Hi,
I agree with your thinking specially about keeping multiple messages with the same key because it is a very common case. Also regarding the frontend, yes browsers do not render the page and just redirect.

**Comment by dbu** [comment]
fixed in #559
