### ISSUE TITLE
PHP 8.1 Attempted to load class "ConfigurationAnnotation" from namespace "Sensio\Bundle\FrameworkExtraBundle\Configuration"

### ISSUE THREAD

**Issue by Claod44** [FriendsOfSymfony/FOSHttpCacheBundle#588]
Hello,

Simple question and if you can point me to a solution it would be really nice...

Symfony 6.2 made sensiolabs framework bundle deprecated...
I use php attribute and I setup the bundle with :

    tags:
        enabled: true
        annotations:
            enabled: false

But I have this message :

Attempted to load class "ConfigurationAnnotation" from namespace "Sensio\Bundle\FrameworkExtraBundle\Configuration".
Did you forget a "use" statement for another namespace?

The error comes from :

namespace FOS\HttpCacheBundle\Configuration;

use FOS\HttpCacheBundle\Exception\InvalidTagException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ConfigurationAnnotation;
use Symfony\Component\Config\Definition\Exception\InvalidConfigurationException;
use Symfony\Component\ExpressionLanguage\ExpressionLanguage;

/**
 * @Annotation
 */
#[\Attribute(\Attribute::IS_REPEATABLE | \Attribute::TARGET_CLASS | \Attribute::TARGET_METHOD)]
class Tag extends ConfigurationAnnotation

There is a

use Sensio\Bundle\FrameworkExtraBundle\Configuration\ConfigurationAnnotation;

But it's deprecated and even this class is using php attributes ...

Any way to get ride of the sensiolabs bundle and annottaions ?

Is the bundle still a real dependency ? And if not how can I solve this message... please ?

**Comment by dbu** [comment]
sorry for the late response. symfony itself is moving to the PHP native attributes that use `#[TagName(attributes)]` that are available since PHP 8.0

FOSHttpCache still supports PHP 7 as well, but for PHP 8 the native syntax works: https://foshttpcachebundle.readthedocs.io/en/latest/reference/annotations.html

the CI build has been green just a few days ago: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/actions/runs/4637027964/jobs/8205503509 so even though sensio framework extra bundle is deprecated, it should not break.

going forward, i think the next major version should move to only php 8 and use native attributes only and get rid of sensio framework extra bundle. i have no urgent plans to do that, but pull requests are welcome.
